# Generated by Django 5.1.4 on 2026-01-21 12:22

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0011_alter_accountmapping_transaction_type_and_more'),
        ('inventory', '0002_alter_category_created_by_alter_category_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stockmovement',
            options={'ordering': ['-movement_date', '-created_at']},
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='movement_number',
            field=models.CharField(blank=True, default='', editable=False, max_length=50),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='source',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('purchase', 'Purchase Order'), ('sales', 'Sales Invoice'), ('production', 'Production'), ('return', 'Return'), ('opening', 'Opening Balance')], default='manual', max_length=20),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='to_warehouse',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='incoming_movements', to='inventory.warehouse'),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='total_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='stockmovement',
            name='unit_cost',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('in', 'Stock In'), ('out', 'Stock Out'), ('transfer', 'Transfer'), ('adjustment_plus', 'Adjustment (+)'), ('adjustment_minus', 'Adjustment (-)')], max_length=20),
        ),
    ]
