# Generated by Django 5.1.4 on 2026-02-03 13:03

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_is_fixed_deposit_field'),
        ('inventory', '0004_consumable_request'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax Code determines VAT rate. No selection = Out of Scope (0%)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory_items', to='finance.taxcode'),
        ),
        migrations.AlterField(
            model_name='item',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
