# Generated by Django 5.1.4 on 2026-02-07 09:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_add_tax_code_to_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='condition_changed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='condition_notes',
            field=models.TextField(blank=True, help_text='Notes about current condition (e.g., assigned to whom, repair details)'),
        ),
        migrations.AddField(
            model_name='item',
            name='condition_status',
            field=models.CharField(choices=[('in_store', 'In Store / Warehouse'), ('in_use', 'In Use'), ('repair', 'Under Repair'), ('damaged', 'Damaged')], default='in_store', help_text='Current condition: In Store, In Use, Under Repair, or Damaged', max_length=20),
        ),
        migrations.CreateModel(
            name='ConditionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('in_store', 'In Store / Warehouse'), ('in_use', 'In Use'), ('repair', 'Under Repair'), ('damaged', 'Damaged')], max_length=20)),
                ('to_status', models.CharField(choices=[('in_store', 'In Store / Warehouse'), ('in_use', 'In Use'), ('repair', 'Under Repair'), ('damaged', 'Damaged')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='condition_logs', to='inventory.item')),
            ],
            options={
                'ordering': ['-changed_at'],
            },
        ),
    ]
