# Generated by Django 5.1.4 on 2026-01-09 10:33

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
        ('finance', '0005_make_reconciliation_number_unique'),
        ('purchase', '0002_vendorbill_journal_entry_alter_vendorbill_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankreconciliation',
            name='opening_balance',
        ),
        migrations.AddField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('opening', 'Opening Balance'), ('adjustment', 'Adjustment'), ('reversal', 'Reversal'), ('closing', 'Closing Entry')], default='standard', max_length=20),
        ),
        migrations.CreateModel(
            name='FXRevaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('revaluation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('revaluation_date', models.DateField()),
                ('total_gain', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_loss', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('net_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.fiscalyear')),
                ('fx_gain_account', models.ForeignKey(help_text='FX Gain account (Income)', on_delete=django.db.models.deletion.PROTECT, related_name='fx_gain_revaluations', to='finance.account')),
                ('fx_loss_account', models.ForeignKey(help_text='FX Loss account (Expense)', on_delete=django.db.models.deletion.PROTECT, related_name='fx_loss_revaluations', to='finance.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fx_revaluation', to='finance.journalentry')),
                ('period', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='finance.accountingperiod')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_fx_revaluations', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-revaluation_date'],
            },
        ),
        migrations.CreateModel(
            name='FXRevaluationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency_code', models.CharField(max_length=3)),
                ('original_amount_fc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('original_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('original_amount_bc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('new_rate', models.DecimalField(decimal_places=6, max_digits=12)),
                ('new_amount_bc', models.DecimalField(decimal_places=2, max_digits=15)),
                ('fx_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('revaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.fxrevaluation')),
            ],
            options={
                'ordering': ['account__code'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('entry_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('entry_type', models.CharField(choices=[('gl', 'General Ledger'), ('bank', 'Bank Account'), ('ar', 'Accounts Receivable'), ('ap', 'Accounts Payable')], max_length=10)),
                ('entry_date', models.DateField()),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('total_debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('total_credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('fiscal_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='opening_balances', to='finance.fiscalyear')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_entry', to='finance.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_opening_balances', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Opening Balance Entry',
                'verbose_name_plural': 'Opening Balance Entries',
                'ordering': ['-entry_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OpeningBalanceLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(blank=True, max_length=500)),
                ('debit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('credit', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('reference_date', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='finance.account')),
                ('bank_account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_lines', to='finance.bankaccount')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_lines', to='crm.customer')),
                ('opening_balance_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='finance.openingbalanceentry')),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opening_balance_lines', to='purchase.vendor')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='WriteOff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('writeoff_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('writeoff_type', models.CharField(choices=[('bad_debt', 'Bad Debt Write-Off'), ('rounding', 'Rounding Difference'), ('short_payment', 'Short Payment'), ('excess_payment', 'Excess Payment'), ('discount', 'Discount Given'), ('fx_adjustment', 'FX Adjustment'), ('other', 'Other Adjustment')], max_length=20)),
                ('writeoff_date', models.DateField()),
                ('description', models.TextField()),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference_type', models.CharField(blank=True, max_length=50)),
                ('reference_number', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('approved', 'Approved'), ('posted', 'Posted'), ('reversed', 'Reversed')], default='draft', max_length=20)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('posted_date', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to='crm.customer')),
                ('expense_account', models.ForeignKey(help_text='Expense account to charge (e.g., Bad Debt Expense)', on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_expense', to='finance.account')),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoff_entry', to='finance.journalentry')),
                ('posted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_writeoffs', to=settings.AUTH_USER_MODEL)),
                ('source_account', models.ForeignKey(help_text='Account to write off from (e.g., AR for bad debt)', on_delete=django.db.models.deletion.PROTECT, related_name='writeoff_source', to='finance.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='writeoffs', to='purchase.vendor')),
            ],
            options={
                'ordering': ['-writeoff_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('currency_code', models.CharField(help_text='ISO 4217 currency code (e.g., USD, EUR)', max_length=3)),
                ('rate_date', models.DateField()),
                ('rate', models.DecimalField(decimal_places=6, help_text='Rate to convert to base currency (AED)', max_digits=12)),
                ('source', models.CharField(blank=True, help_text='Rate source (e.g., UAE Central Bank)', max_length=100)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-rate_date', 'currency_code'],
                'unique_together': {('currency_code', 'rate_date')},
            },
        ),
    ]
