# Generated by Django 5.1.4 on 2026-01-14 17:55

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_account_created_by_alter_account_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_post_sales_invoice', models.BooleanField(default=True, help_text='Auto-post journal when sales invoice is approved')),
                ('auto_post_vendor_bill', models.BooleanField(default=True, help_text='Auto-post journal when vendor bill is approved')),
                ('auto_post_expense_claim', models.BooleanField(default=True, help_text='Auto-post journal when expense claim is approved')),
                ('auto_post_payroll', models.BooleanField(default=True, help_text='Auto-post journal when payroll is processed')),
                ('auto_post_payment', models.BooleanField(default=True, help_text='Auto-post journal when payment is confirmed')),
                ('auto_post_bank_transfer', models.BooleanField(default=True, help_text='Auto-post journal when bank transfer is confirmed')),
                ('require_approval_before_posting', models.BooleanField(default=True, help_text='Documents must be approved before posting to ledger')),
                ('allow_posting_to_closed_period', models.BooleanField(default=False, help_text='Allow posting to closed accounting periods (not recommended)')),
                ('default_vat_rate', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Default VAT rate for transactions', max_digits=5)),
                ('vat_registration_number', models.CharField(blank=True, max_length=50)),
                ('round_to_fils', models.BooleanField(default=True, help_text='Round amounts to 2 decimal places (fils)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Accounting Settings',
                'verbose_name_plural': 'Accounting Settings',
            },
        ),
        migrations.CreateModel(
            name='AccountMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('sales', 'Sales'), ('purchase', 'Purchase'), ('expense_claim', 'Expense Claims'), ('payroll', 'Payroll'), ('banking', 'Banking'), ('inventory', 'Inventory'), ('general', 'General')], max_length=50)),
                ('transaction_type', models.CharField(choices=[('sales_invoice_receivable', 'Sales Invoice - Accounts Receivable'), ('sales_invoice_revenue', 'Sales Invoice - Sales Revenue'), ('sales_invoice_vat', 'Sales Invoice - VAT Payable'), ('sales_invoice_discount', 'Sales Invoice - Sales Discount'), ('customer_receipt', 'Customer Receipt - Bank'), ('customer_receipt_ar_clear', 'Customer Receipt - AR Clearing'), ('vendor_bill_payable', 'Vendor Bill - Accounts Payable'), ('vendor_bill_expense', 'Vendor Bill - Default Expense'), ('vendor_bill_vat', 'Vendor Bill - VAT Recoverable'), ('vendor_payment', 'Vendor Payment - Bank'), ('vendor_payment_ap_clear', 'Vendor Payment - AP Clearing'), ('expense_claim_expense', 'Expense Claim - Default Expense'), ('expense_claim_vat', 'Expense Claim - VAT Recoverable'), ('expense_claim_payable', 'Expense Claim - Employee Payable'), ('expense_claim_payment', 'Expense Claim Payment - Bank'), ('expense_claim_clear', 'Expense Claim Payment - Clear Payable'), ('payroll_salary_expense', 'Payroll - Salary Expense'), ('payroll_salary_payable', 'Payroll - Salary Payable'), ('payroll_gratuity_expense', 'Payroll - Gratuity Expense'), ('payroll_gratuity_payable', 'Payroll - Gratuity Payable'), ('payroll_pension_expense', 'Payroll - Pension Expense'), ('payroll_pension_payable', 'Payroll - Pension Payable'), ('payroll_wps_deduction', 'Payroll - WPS Deduction'), ('payroll_payment', 'Payroll Payment - Bank'), ('payroll_payment_clear', 'Payroll Payment - Clear Payable'), ('bank_charges', 'Bank Charges Expense'), ('bank_interest_income', 'Bank Interest Income'), ('bank_interest_expense', 'Bank Interest Expense'), ('bank_transfer', 'Bank Transfer - Inter-bank'), ('fx_gain', 'Foreign Exchange Gain'), ('fx_loss', 'Foreign Exchange Loss'), ('retained_earnings', 'Retained Earnings'), ('opening_balance_equity', 'Opening Balance Equity'), ('suspense', 'Suspense Account'), ('rounding', 'Rounding Difference')], max_length=50, unique=True)),
                ('description', models.CharField(blank=True, max_length=200)),
                ('is_mandatory', models.BooleanField(default=True, help_text='If true, transaction will fail without this mapping')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='account_mappings', to='finance.account')),
            ],
            options={
                'verbose_name': 'Account Mapping',
                'verbose_name_plural': 'Account Mappings',
                'ordering': ['module', 'transaction_type'],
            },
        ),
    ]
