# Generated by Django 5.1.4 on 2026-01-18 07:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_mapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='adjustment_details',
            field=models.JSONField(blank=True, default=dict, help_text='Detailed breakdown of adjustments for audit'),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='payment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tax_payments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='provision_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='provision_posted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='corporatetaxcomputation',
            name='taxable_amount_above_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AlterField(
            model_name='accountmapping',
            name='transaction_type',
            field=models.CharField(choices=[('sales_invoice_receivable', 'Sales Invoice - Accounts Receivable'), ('sales_invoice_revenue', 'Sales Invoice - Sales Revenue'), ('sales_invoice_vat', 'Sales Invoice - VAT Payable'), ('sales_invoice_discount', 'Sales Invoice - Sales Discount'), ('customer_receipt', 'Customer Receipt - Bank'), ('customer_receipt_ar_clear', 'Customer Receipt - AR Clearing'), ('vendor_bill_payable', 'Vendor Bill - Accounts Payable'), ('vendor_bill_expense', 'Vendor Bill - Default Expense'), ('vendor_bill_vat', 'Vendor Bill - VAT Recoverable'), ('vendor_payment', 'Vendor Payment - Bank'), ('vendor_payment_ap_clear', 'Vendor Payment - AP Clearing'), ('expense_claim_expense', 'Expense Claim - Default Expense'), ('expense_claim_vat', 'Expense Claim - VAT Recoverable'), ('expense_claim_payable', 'Expense Claim - Employee Payable'), ('expense_claim_payment', 'Expense Claim Payment - Bank'), ('expense_claim_clear', 'Expense Claim Payment - Clear Payable'), ('payroll_salary_expense', 'Payroll - Salary Expense'), ('payroll_salary_payable', 'Payroll - Salary Payable'), ('payroll_gratuity_expense', 'Payroll - Gratuity Expense'), ('payroll_gratuity_payable', 'Payroll - Gratuity Payable'), ('payroll_pension_expense', 'Payroll - Pension Expense'), ('payroll_pension_payable', 'Payroll - Pension Payable'), ('payroll_wps_deduction', 'Payroll - WPS Deduction'), ('payroll_payment', 'Payroll Payment - Bank'), ('payroll_payment_clear', 'Payroll Payment - Clear Payable'), ('bank_charges', 'Bank Charges Expense'), ('bank_interest_income', 'Bank Interest Income'), ('bank_interest_expense', 'Bank Interest Expense'), ('bank_transfer', 'Bank Transfer - Inter-bank'), ('corporate_tax_expense', 'Corporate Tax - Tax Expense'), ('corporate_tax_payable', 'Corporate Tax - Tax Payable'), ('vat_output', 'VAT - Output Tax Payable'), ('vat_input', 'VAT - Input Tax Recoverable'), ('vat_payable', 'VAT - Net Payable Account'), ('fx_gain', 'Foreign Exchange Gain'), ('fx_loss', 'Foreign Exchange Loss'), ('retained_earnings', 'Retained Earnings'), ('opening_balance_equity', 'Opening Balance Equity'), ('suspense', 'Suspense Account'), ('rounding', 'Rounding Difference')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='corporatetaxcomputation',
            name='exempt_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Qualifying dividends, capital gains on qualifying shareholdings', max_digits=15),
        ),
        migrations.AlterField(
            model_name='corporatetaxcomputation',
            name='non_deductible_expenses',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Fines, penalties, non-business expenses, entertainment', max_digits=15),
        ),
        migrations.AlterField(
            model_name='corporatetaxcomputation',
            name='other_adjustments',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Depreciation adjustments, provisions, etc.', max_digits=15),
        ),
        migrations.AlterField(
            model_name='corporatetaxcomputation',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('final', 'Final'), ('filed', 'Filed'), ('paid', 'Paid')], default='draft', max_length=20),
        ),
        migrations.AlterField(
            model_name='corporatetaxcomputation',
            name='tax_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('9.00'), help_text='UAE Corporate Tax rate (%)', max_digits=5),
        ),
        migrations.AlterField(
            model_name='corporatetaxcomputation',
            name='tax_threshold',
            field=models.DecimalField(decimal_places=2, default=Decimal('375000.00'), help_text='Small business relief threshold (AED 375,000)', max_digits=15),
        ),
    ]
