# Generated by Django 5.1.4 on 2026-01-18 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0009_corporate_tax_improvements'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('sales', 'Sales Invoice'), ('purchase', 'Vendor Bill'), ('payment', 'Payment'), ('bank_transfer', 'Bank Transfer'), ('expense_claim', 'Expense Claim'), ('payroll', 'Payroll'), ('vat', 'VAT Adjustment'), ('corporate_tax', 'Corporate Tax'), ('opening_balance', 'Opening Balance'), ('year_end', 'Year-End Closing')], default='manual', help_text='Module that created this journal entry', max_length=50),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='entry_type',
            field=models.CharField(choices=[('standard', 'Standard'), ('opening', 'Opening Balance'), ('adjustment', 'Adjustment'), ('adjusting', 'Adjusting Entry'), ('reversal', 'Reversal'), ('closing', 'Closing Entry')], default='standard', max_length=20),
        ),
    ]
