# Generated by Django 5.1.4 on 2026-01-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0014_alter_accountmapping_transaction_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='journalentry',
            name='is_locked',
            field=models.BooleanField(default=False, help_text='Locked journals cannot be edited or deleted'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='is_system_generated',
            field=models.BooleanField(default=False, help_text='True if auto-generated by system (invoice, bill, payroll, etc.)'),
        ),
        migrations.AddField(
            model_name='journalentry',
            name='source_id',
            field=models.PositiveIntegerField(blank=True, help_text='ID of the source document that created this journal', null=True),
        ),
        migrations.AlterField(
            model_name='journalentry',
            name='source_module',
            field=models.CharField(choices=[('manual', 'Manual Entry'), ('sales', 'Sales Invoice'), ('purchase', 'Vendor Bill'), ('payment', 'Payment'), ('bank_transfer', 'Bank Transfer'), ('expense_claim', 'Expense Claim'), ('payroll', 'Payroll'), ('inventory', 'Inventory Movement'), ('fixed_asset', 'Fixed Asset'), ('project', 'Project Expense'), ('pdc', 'PDC Cheque'), ('property', 'Property/Rent'), ('vat', 'VAT Adjustment'), ('corporate_tax', 'Corporate Tax'), ('opening_balance', 'Opening Balance'), ('year_end', 'Year-End Closing'), ('reversal', 'Reversal Entry'), ('adjustment', 'Manual Adjustment')], default='manual', help_text='Module that created this journal entry', max_length=50),
        ),
    ]
