# Generated by Django 5.1.4 on 2026-01-27 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0015_add_journal_entry_standards'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_cash_account',
            field=models.BooleanField(default=False, help_text='Mark as True for Bank and Cash accounts only. Used for Cash Flow Statement.'),
        ),
    ]
