# Generated by Django 5.1.4 on 2026-01-28 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0016_add_is_cash_account_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='account_category',
            field=models.CharField(blank=True, choices=[('cash_bank', 'Cash & Bank'), ('trade_receivables', 'Trade Receivables'), ('tax_receivables', 'Taxes & Statutory Receivables'), ('inventory', 'Inventory'), ('prepaid', 'Prepaid Expenses'), ('other_current_assets', 'Other Current Assets'), ('fixed_furniture', 'Furniture & Fixtures'), ('fixed_it', 'IT Equipment'), ('fixed_vehicles', 'Vehicles'), ('fixed_other', 'Other Fixed Assets'), ('accum_depreciation', 'Accumulated Depreciation'), ('intangible', 'Intangible Assets'), ('trade_payables', 'Trade Payables'), ('tax_payables', 'Taxes Payable'), ('accrued_liabilities', 'Accrued Liabilities'), ('other_current_liabilities', 'Other Current Liabilities'), ('long_term_liabilities', 'Long Term Liabilities'), ('capital', 'Capital Accounts'), ('reserves', 'Reserves & Surplus'), ('retained_earnings', 'Retained Earnings'), ('operating_revenue', 'Operating Revenue'), ('other_income', 'Other Income'), ('cost_of_sales', 'Cost of Sales'), ('rent_expense', 'Rent Expenses'), ('salary_expense', 'Salary & Staff Costs'), ('banking_expense', 'Banking Expenses'), ('bad_debts', 'Bad Debts'), ('depreciation_expense', 'Depreciation'), ('utilities', 'Utilities'), ('project_costs', 'Project Costs'), ('marketing', 'Marketing'), ('admin_expense', 'Administrative Expenses'), ('other_expense', 'Other Expenses')], help_text='Category for grouping in Trial Balance and Financial Statements', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='is_contra_account',
            field=models.BooleanField(default=False, help_text='Contra accounts have opposite normal balance (e.g., Accumulated Depreciation)'),
        ),
    ]
