# Generated by Django 5.1.4 on 2026-01-29 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0017_add_account_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='overdraft_allowed',
            field=models.BooleanField(default=False, help_text='Allow credit (negative) balance for this account. Only applicable to bank accounts.'),
        ),
    ]
