# Generated by Django 5.1.4 on 2026-01-30 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0018_add_overdraft_allowed_to_account'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='is_fixed_deposit',
            field=models.BooleanField(default=False, help_text='Mark as True for Fixed Deposit accounts. These are EXCLUDED from Cash Flow Statement opening/closing balance.'),
        ),
    ]
