# Generated by Django 5.1.4 on 2026-02-05 13:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_is_fixed_deposit_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vatreturn',
            name='is_period_locked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_returns', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='posted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posted_vat_returns', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='posted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='vatreturn',
            name='reversal_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vat_return_reversals', to='finance.journalentry'),
        ),
        migrations.AlterField(
            model_name='vatreturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('submitted', 'Submitted'), ('accepted', 'Accepted'), ('amended', 'Amended')], default='draft', max_length=20),
        ),
    ]
