# Generated by Django 5.1.4 on 2026-03-02 20:25

from django.db import migrations, models


# Comprehensive mapping of account codes → (account_category, is_cash_account, cash_flow_classification)
ACCOUNT_DATA_FIX = {
    # Cash & Bank → Operating (they ARE the cash accounts, not counter-accounts)
    '1000':   ('cash_bank',          True,  'excluded'),
    '100001': ('cash_bank',          True,  'excluded'),
    '1100':   ('cash_bank',          True,  'excluded'),
    # Trade Receivables → Operating
    '1200':   ('trade_receivables',  False, 'operating'),
    '1210':   ('trade_receivables',  False, 'operating'),
    '1211':   ('trade_receivables',  False, 'operating'),
    '1212':   ('trade_receivables',  False, 'operating'),
    '1213':   ('trade_receivables',  False, 'operating'),
    # Tax Receivables → Operating  (already has category)
    '1300':   ('tax_receivables',    False, 'operating'),
    # Fixed Assets → Investing
    '1400':   ('fixed_furniture',    False, 'investing'),
    '1401':   ('accum_depreciation', False, 'investing'),
    '1410':   ('fixed_it',           False, 'investing'),
    '1411':   ('accum_depreciation', False, 'investing'),
    # Inventory → Operating
    '1500':   ('inventory',          False, 'operating'),
    # Accounts Payable / Current Liabilities → Operating
    '2000':   ('trade_payables',     False, 'operating'),
    '2010':   ('trade_payables',     False, 'operating'),
    '2100':   ('accrued_liabilities', False, 'operating'),
    '2150':   ('other_current_assets', False, 'operating'),
    '2200':   ('accrued_liabilities', False, 'operating'),
    '2300':   ('other_current_liabilities', False, 'operating'),
    # Tax Payables → Operating  (already has category for some)
    '2110':   ('tax_payables',       False, 'operating'),
    '2120':   ('tax_payables',       False, 'operating'),
    '2400':   ('tax_payables',       False, 'operating'),
    # Equity → Financing
    '3000':   ('capital',            False, 'financing'),
    '3100':   ('retained_earnings',  False, 'financing'),
    # Revenue → Operating
    '4000':   ('operating_revenue',  False, 'operating'),
    '4100':   ('other_income',       False, 'operating'),
    '4500':   ('other_income',       False, 'operating'),
    # Expenses → Operating
    '5000':   ('cost_of_sales',      False, 'operating'),
    '5100':   ('cost_of_sales',      False, 'operating'),
    '5200':   ('cost_of_sales',      False, 'operating'),
    '5300':   ('salary_expense',     False, 'operating'),
    '5500':   ('depreciation_expense', False, 'excluded'),
    '6000':   ('other_expense',      False, 'operating'),
    '6100':   ('rent_expense',       False, 'operating'),
    '6200':   ('marketing',          False, 'operating'),
    '6300':   ('utilities',          False, 'operating'),
    '6500':   ('other_expense',      False, 'operating'),
    '6510':   ('bad_debts',          False, 'operating'),
    '6600':   ('other_expense',      False, 'operating'),
    '6700':   ('other_expense',      False, 'operating'),
}


def fix_account_data(apps, schema_editor):
    """
    Set account_category, is_cash_account, and cash_flow_classification
    for every account in the chart of accounts.
    """
    Account = apps.get_model('finance', 'Account')

    for code, (category, is_cash, cf_class) in ACCOUNT_DATA_FIX.items():
        Account.objects.filter(code=code).update(
            account_category=category,
            is_cash_account=is_cash,
            cash_flow_classification=cf_class,
        )

    # Fallback: set sensible defaults for any accounts NOT in the map
    # Asset accounts without category → other_current_assets
    Account.objects.filter(
        account_type='asset',
        account_category__isnull=True,
    ).update(account_category='other_current_assets')
    Account.objects.filter(
        account_type='asset',
        account_category='',
    ).update(account_category='other_current_assets')

    # Liability accounts without category → other_current_liabilities
    Account.objects.filter(
        account_type='liability',
        account_category__isnull=True,
    ).update(account_category='other_current_liabilities')
    Account.objects.filter(
        account_type='liability',
        account_category='',
    ).update(account_category='other_current_liabilities')

    # Income without category → operating_revenue
    Account.objects.filter(
        account_type='income',
        account_category__isnull=True,
    ).update(account_category='operating_revenue')
    Account.objects.filter(
        account_type='income',
        account_category='',
    ).update(account_category='operating_revenue')

    # Expense without category → other_expense
    Account.objects.filter(
        account_type='expense',
        account_category__isnull=True,
    ).update(account_category='other_expense')
    Account.objects.filter(
        account_type='expense',
        account_category='',
    ).update(account_category='other_expense')

    # Equity without category → capital
    Account.objects.filter(
        account_type='equity',
        account_category__isnull=True,
    ).update(account_category='capital')
    Account.objects.filter(
        account_type='equity',
        account_category='',
    ).update(account_category='capital')


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0024_vat_return_fta_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='cash_flow_classification',
            field=models.CharField(
                choices=[
                    ('auto', 'Automatic (Derived)'),
                    ('operating', 'Operating'),
                    ('investing', 'Investing'),
                    ('financing', 'Financing'),
                    ('excluded', 'Excluded from Cash Flow'),
                ],
                default='auto',
                help_text=(
                    "Cash flow statement classification for this account. "
                    "'Auto' derives classification from account type and category."
                ),
                max_length=20,
            ),
        ),
        migrations.RunPython(fix_account_data, migrations.RunPython.noop),
    ]
