# Generated by Django 5.1.4 on 2026-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_add_credit_notes_petty_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoiceitem',
            name='is_vat_inclusive',
            field=models.BooleanField(default=False, help_text='If true, unit_price includes VAT'),
        ),
        migrations.AddField(
            model_name='quotationitem',
            name='is_vat_inclusive',
            field=models.BooleanField(default=False, help_text='If true, unit_price includes VAT'),
        ),
    ]
