# Generated by Django 5.1.4 on 2026-01-09 09:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0003_add_budget_banktransfer_reconciliation'),
        ('purchase', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendorbill',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vendor_bills', to='finance.journalentry'),
        ),
        migrations.AlterField(
            model_name='vendorbill',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('posted', 'Posted'), ('pending', 'Pending'), ('paid', 'Paid'), ('partial', 'Partially Paid'), ('overdue', 'Overdue')], default='draft', max_length=20),
        ),
    ]
