# Generated by Django 5.1.4 on 2026-01-14 17:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0003_alter_purchaseorder_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringexpenselog',
            name='vendor_bill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recurring_expense_logs', to='purchase.vendorbill'),
        ),
    ]
