# Generated by Django 5.1.4 on 2026-01-22 10:24

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0005_add_credit_notes_petty_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='country',
            field=models.CharField(default='United Arab Emirates', max_length=100),
        ),
        migrations.AddField(
            model_name='vendor',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='vendor',
            name='payment_terms',
            field=models.CharField(blank=True, default='Net 30', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='trn',
            field=models.CharField(blank=True, help_text='UAE VAT TRN for B2B transactions', max_length=20, verbose_name='Tax Registration Number (TRN)'),
        ),
    ]
