# Generated by Django 5.1.4 on 2026-01-23 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase', '0006_vendor_city_vendor_country_vendor_credit_limit_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorderitem',
            name='is_vat_inclusive',
            field=models.BooleanField(default=False, help_text='If true, unit_price includes VAT'),
        ),
        migrations.AddField(
            model_name='vendorbillitem',
            name='is_vat_inclusive',
            field=models.BooleanField(default=False, help_text='If true, unit_price includes VAT'),
        ),
    ]
