# Generated by Django 5.1.4 on 2026-02-03 11:38

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0019_add_is_fixed_deposit_field'),
        ('purchase', '0007_purchaseorderitem_is_vat_inclusive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expenseclaimitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax Code determines VAT rate. No selection = Out of Scope (0%)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='expense_claim_items', to='finance.taxcode'),
        ),
        migrations.AddField(
            model_name='purchasecreditnoteitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax Code determines VAT rate. No selection = Out of Scope (0%)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_credit_note_items', to='finance.taxcode'),
        ),
        migrations.AddField(
            model_name='purchaseorderitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax Code determines VAT rate. No selection = Out of Scope (0%)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='purchase_order_items', to='finance.taxcode'),
        ),
        migrations.AddField(
            model_name='vendorbillitem',
            name='tax_code',
            field=models.ForeignKey(blank=True, help_text='Tax Code determines VAT rate. No selection = Out of Scope (0%)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='vendor_bill_items', to='finance.taxcode'),
        ),
        migrations.AlterField(
            model_name='purchasecreditnoteitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='purchaseorderitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
        migrations.AlterField(
            model_name='vendorbillitem',
            name='vat_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=5),
        ),
    ]
