# Generated by Django 5.1.4 on 2026-01-14 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0008_account_mapping'),
        ('hr', '0003_alter_department_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payroll',
            name='journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_entries', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payroll',
            name='paid_from_bank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.bankaccount'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_journal_entry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payroll_payments', to='finance.journalentry'),
        ),
        migrations.AddField(
            model_name='payroll',
            name='payment_reference',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
