# Generated by Django 5.1.4 on 2026-01-13 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='country',
            field=models.CharField(default='United Arab Emirates', max_length=100),
        ),
        migrations.AddField(
            model_name='customer',
            name='trn',
            field=models.CharField(blank=True, help_text='UAE VAT TRN for B2B invoices', max_length=20, verbose_name='Tax Registration Number (TRN)'),
        ),
    ]
