# Generated by Django 5.1.4 on 2026-01-21 12:21

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('finance', '0011_alter_accountmapping_transaction_type_and_more'),
        ('purchase', '0004_account_mapping'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=50)),
                ('useful_life_years', models.IntegerField(default=5, help_text='Default useful life in years')),
                ('salvage_value_percent', models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Salvage value as % of cost', max_digits=5)),
                ('accumulated_depreciation_account', models.ForeignKey(blank=True, help_text='Accumulated Depreciation GL Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accum_depreciation_categories', to='finance.account')),
                ('asset_account', models.ForeignKey(blank=True, help_text='Asset GL Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='asset_categories', to='finance.account')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('depreciation_expense_account', models.ForeignKey(blank=True, help_text='Depreciation Expense GL Account', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='depreciation_expense_categories', to='finance.account')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Asset Categories',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='FixedAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('asset_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('fully_depreciated', 'Fully Depreciated'), ('disposed', 'Disposed'), ('written_off', 'Written Off')], default='draft', max_length=20)),
                ('serial_number', models.CharField(blank=True, max_length=100)),
                ('location', models.CharField(blank=True, max_length=200)),
                ('acquisition_date', models.DateField()),
                ('acquisition_cost', models.DecimalField(decimal_places=2, max_digits=15)),
                ('purchase_invoice', models.CharField(blank=True, max_length=100)),
                ('depreciation_method', models.CharField(choices=[('straight_line', 'Straight Line'), ('declining_balance', 'Declining Balance'), ('units_of_production', 'Units of Production')], default='straight_line', max_length=50)),
                ('useful_life_years', models.IntegerField(default=5)),
                ('useful_life_months', models.IntegerField(default=60)),
                ('salvage_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('depreciation_start_date', models.DateField(blank=True, null=True)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('book_value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('last_depreciation_date', models.DateField(blank=True, null=True)),
                ('disposal_date', models.DateField(blank=True, null=True)),
                ('disposal_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('disposal_reason', models.TextField(blank=True)),
                ('gain_loss_on_disposal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('acquisition_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_acquisitions', to='finance.journalentry')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assets', to='assets.assetcategory')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('custodian', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_assets', to=settings.AUTH_USER_MODEL)),
                ('disposal_journal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='asset_disposals', to='finance.journalentry')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('vendor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assets_supplied', to='purchase.vendor')),
            ],
            options={
                'ordering': ['-acquisition_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='AssetDepreciation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('depreciation_date', models.DateField()),
                ('depreciation_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('accumulated_depreciation', models.DecimalField(decimal_places=2, max_digits=15)),
                ('book_value_after', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('journal_entry', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finance.journalentry')),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='depreciation_records', to='assets.fixedasset')),
            ],
            options={
                'ordering': ['-depreciation_date'],
                'unique_together': {('asset', 'depreciation_date')},
            },
        ),
    ]
