# Generated by Django 5.1.4 on 2026-03-02 19:48

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


def backfill_period(apps, schema_editor):
    """Populate period (YYYY-MM) from depreciation_date for existing records."""
    AssetDepreciation = apps.get_model('assets', 'AssetDepreciation')
    for record in AssetDepreciation.objects.all():
        record.period = record.depreciation_date.strftime('%Y-%m')
        record.save(update_fields=['period'])


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assetdepreciation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='depreciation_start_policy',
            field=models.CharField(choices=[('acquisition_date', 'From Acquisition Date'), ('next_month', 'First Day of Following Month')], default='acquisition_date', help_text='When depreciation should begin', max_length=20),
        ),
        migrations.AddField(
            model_name='assetcategory',
            name='partial_month_policy',
            field=models.CharField(choices=[('full_month', 'Full Month Depreciation'), ('pro_rata', 'Pro-Rata (Days-Based)'), ('mid_month', 'Mid-Month Convention')], default='full_month', help_text='How to handle depreciation in the acquisition month', max_length=20),
        ),
        migrations.AddField(
            model_name='assetdepreciation',
            name='period',
            field=models.CharField(db_index=True, default='', help_text='YYYY-MM', max_length=7),
        ),
        migrations.RunPython(backfill_period, migrations.RunPython.noop),
        migrations.AlterUniqueTogether(
            name='assetdepreciation',
            unique_together={('asset', 'period')},
        ),
        migrations.CreateModel(
            name='DepreciationBatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('depreciation_date', models.DateField()),
                ('period', models.CharField(db_index=True, help_text='YYYY-MM', max_length=7)),
                ('run_date', models.DateTimeField(auto_now_add=True)),
                ('total_assets', models.IntegerField(default=0)),
                ('success_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('skip_count', models.IntegerField(default=0)),
                ('total_depreciation', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
                ('status', models.CharField(choices=[('running', 'Running'), ('completed', 'Completed'), ('completed_with_errors', 'Completed with Errors'), ('failed', 'Failed')], default='running', max_length=25)),
                ('notes', models.TextField(blank=True)),
                ('error_details', models.JSONField(blank=True, default=dict)),
                ('run_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-run_date'],
            },
        ),
        migrations.AddField(
            model_name='assetdepreciation',
            name='batch_run',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depreciation_records', to='assets.depreciationbatchrun'),
        ),
    ]
